name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
         deploy_key: zjx  # 上文保存至本仓库secrets中的ssh秘钥变量名
         external_repository: git@github.com:jnpd/zuozuo.git # 需要将静态文件推送的仓库名
         publish_branch: main # 对应目的仓库的目的分支，因为waouooo主分支为main
         publish_dir: ./public # 推送的文件夹，hugo --minify命令会将静态文件生成至./public文件夹中
         commit_message: ${{ github.event.head_commit.message }} # 指定commit信息
